name: "gogithub" 
description: "gogithub example"

inputs:
  files:
    description: List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
    required: true
  version:
    description: Version of the bicep CLI. It can be the exact version (eg. `v0.3.255`), wildcard (eg. `v0.3.x`) or `latest`. If omitted, `latest` is set as default.
    required: false
    default: 'latest'


runs:  
  using: composite 
  steps:
  - run: go run  ${{ github.action_path }}/hellorepo1.go
    shell: bash
    
    runs:  
  using: composite 
  steps:
  - run: go run  ${{ github.action_path }}/hellorepo2.go  ${{ inputs.files }} ${{ inputs.files }}
    shell: bash

