name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
  

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: check out
      uses: actions/checkout@v2

   
    - name: goexample
      used: AdminTurnedDevOps/goexample@v1
